name: Testing site config
type: profile
description: 'Minimal profile for testing with default site config.'
# version: VERSION
hidden: true

# Information added by Drupal.org packaging script on 2023-02-01
version: '9.5.3'
project: 'drupal'
datestamp: 1675281916
